# Generated by Django 2.2.9 on 2020-01-28 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 4, 19, 32, 29, 66290)),
        ),
    ]
