# Generated by Django 3.0.2 on 2020-01-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quantity',
            new_name='quant',
        ),
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.URLField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.CharField(max_length=10),
        ),
    ]
