# Generated by Django 2.2.9 on 2020-01-29 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200129_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 5, 21, 33, 46, 719107)),
        ),
    ]
