# Generated by Django 2.2.9 on 2020-01-29 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200129_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 5, 17, 43, 42, 328931)),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Order'),
        ),
    ]
