# Generated by Django 3.0.2 on 2020-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200127_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quant',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.CharField(default='2010', max_length=15),
        ),
    ]
