# Generated by Django 2.2.9 on 2020-01-30 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200130_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 6, 22, 43, 17, 424838)),
        ),
    ]
