# Generated by Django 3.0.2 on 2020-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200127_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ManyToManyField(to='main_app.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100),
        ),
    ]
